# See tutorial:
#   https://michaelcurrin.github.io/code-cookbook/recipes/ci-cd/github-actions/workflows/node/upgrade-packages.html
name: Upgrade NPM packages

on:
  workflow_dispatch:
  
  #schedule:
  #  - cron: '0 0 * * 0'

jobs:
  upgrade-packages:
    name: Upgrade packages

    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Set up Node.js âš™ï¸
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'

      - name: Check for outdated packages ğŸ”
        id: vars
        run: |
          OUTDATED=$(yarn outdated) || true

          if [[ -z "$OUTDATED" ]]; then
            echo 'Nothing to upgrade'
          else
            echo 'Found outdated packages:'
            echo "$OUTDATED"
          fi

          echo "::set-output name=outdated::$OUTDATED"

      - name: Upgrade packages â«
        if: ${{ steps.vars.outputs.outdated != '' }}
        run: yarn upgrade
        
      - name: Lint ğŸ§
        if: ${{ steps.vars.outputs.outdated != '' }}
        run: yarn lint:check

      - name: Test ğŸš¨
        if: ${{ steps.vars.outputs.outdated != '' }}
        run: yarn test:unit

      - name: Build ğŸ—ï¸
        if: ${{ steps.vars.outputs.outdated != '' }}
        run: yarn build
        env:
          NODE_ENV: production

      - name: Commit and create PR ğŸ”€
        if: ${{ steps.vars.outputs.outdated != '' }}
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'build(deps): Upgrade NPM packages (automated)'
          branch: 'build-deps-upgrade-npm-packages-automated'
          commit-message: 'build(deps): upgrade NPM packages (automated)'
